name: Deploy API to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]
    paths:
      - '5-Deploiement/getaround_project/api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "204518881+AichaFa@users.noreply.github.com"
          git config --global user.name "AichaFa"
          git remote add hf https://AichaFa:$HF_TOKEN@huggingface.co/spaces/AichaFaHugFace/getaround-api
          git subtree push --prefix 5-Deploiement/getaround_project/api hf main